"""Capability-oriented external Tool Ecosystem for Adaptive Agent Runtime."""

from adaptive_agent_runtime.tool_ecosystem.capability import (
    CapabilityResolver,
    ExactCapabilityMatcher,
    InMemoryCapabilityCatalog,
)
from adaptive_agent_runtime.tool_ecosystem.contracts import (
    CapabilityCandidateResolver,
    CapabilityCatalog,
    CapabilityMatcher,
    ToolExecutor,
    ToolExecutionGovernor,
    ToolProvider,
    ToolRegistry,
    ToolSelector,
    ToolTraceSink,
)
from adaptive_agent_runtime.tool_ecosystem.errors import (
    CapabilityAlreadyRegisteredError,
    CapabilityNotFoundError,
    ProviderAlreadyRegisteredError,
    ProviderNotFoundError,
    ProviderUnavailableError,
    ToolEcosystemError,
    ToolIntegrationError,
    ToolSelectionError,
)
from adaptive_agent_runtime.tool_ecosystem.execution import (
    InMemoryToolTraceSink,
    ManagedToolExecutor,
)
from adaptive_agent_runtime.tool_ecosystem.governance import (
    OperationalToolGovernor,
    RetryPolicy,
    ToolExecutionPolicy,
)
from adaptive_agent_runtime.tool_ecosystem.integration import (
    MappedTaskCapabilityRequestProvider,
    TOOL_OBSERVATION_METADATA_KEY,
    TaskCapabilityRequestProvider,
    ToolExecutionStrategy,
    ToolResultObservationAdapter,
)
from adaptive_agent_runtime.tool_ecosystem.models import (
    Capability,
    CapabilityMatch,
    CapabilityRequest,
    CapabilityRequirement,
    ProviderAvailability,
    RetryStatus,
    ToolAttempt,
    ToolAttemptStatus,
    ToolCorrelation,
    ToolExecutionStatus,
    ToolInvocation,
    ToolObservation,
    ToolProviderMetadata,
    ToolProviderResult,
    ToolSelection,
    ToolSelectionContext,
    ToolTraceEntry,
    ToolTraceEvent,
    ToolTraceEventKind,
)
from adaptive_agent_runtime.tool_ecosystem.registry import InMemoryToolRegistry
from adaptive_agent_runtime.tool_ecosystem.selector import DeterministicToolSelector

__all__ = [
    "Capability",
    "CapabilityAlreadyRegisteredError",
    "CapabilityCandidateResolver",
    "CapabilityCatalog",
    "CapabilityMatch",
    "CapabilityMatcher",
    "CapabilityNotFoundError",
    "CapabilityRequest",
    "CapabilityRequirement",
    "CapabilityResolver",
    "DeterministicToolSelector",
    "ExactCapabilityMatcher",
    "InMemoryCapabilityCatalog",
    "InMemoryToolRegistry",
    "InMemoryToolTraceSink",
    "ManagedToolExecutor",
    "MappedTaskCapabilityRequestProvider",
    "OperationalToolGovernor",
    "ProviderAlreadyRegisteredError",
    "ProviderAvailability",
    "ProviderNotFoundError",
    "ProviderUnavailableError",
    "RetryPolicy",
    "RetryStatus",
    "TOOL_OBSERVATION_METADATA_KEY",
    "TaskCapabilityRequestProvider",
    "ToolAttempt",
    "ToolAttemptStatus",
    "ToolEcosystemError",
    "ToolExecutionPolicy",
    "ToolExecutionGovernor",
    "ToolExecutionStatus",
    "ToolExecutionStrategy",
    "ToolExecutor",
    "ToolIntegrationError",
    "ToolInvocation",
    "ToolCorrelation",
    "ToolObservation",
    "ToolProvider",
    "ToolProviderMetadata",
    "ToolProviderResult",
    "ToolRegistry",
    "ToolResultObservationAdapter",
    "ToolSelection",
    "ToolSelectionContext",
    "ToolSelectionError",
    "ToolSelector",
    "ToolTraceEntry",
    "ToolTraceEvent",
    "ToolTraceEventKind",
    "ToolTraceSink",
]
